# Numerical Recipes Workshop 1
For the week of 23-27 September, 2019

These activities will start with a small Python/NumPy refresher and then cover some things related to lectures 1/2 and the first part of Checkpoint 1.

**Please hand in your notebook via Noteable at the end of the workshop.**

They will not be graded and you will not receive feedback on them, but we want to test the submission process to make sure it's working for the checkpoints.

Please spend the first hour of the workshop with this notebook before starting on the checkpoint. **TAs will not answer questions about the checkpoints until the second hour of the workshop.**

## Documentation
* Python: https://docs.python.org/3.7/
* NumPy: https://numpy.org/doc/1.17/user/index.html
* SciPy: https://docs.scipy.org/doc/scipy/reference/
* matplotlib: https://matplotlib.org/3.1.0/index.html

Advice: google is really helpful (e.g. "numpy trapezoid rule")

## Python/package Versions

It's good to know what versions of Python and various packages you're using. Answers can be different or known bugs may exist in specific versions.

Use sys package for Python version. Most external packages have a `__version__` attribute associated with the top level import.

In [1]:
# Python version
import sys
print(sys.version)
# Scipy version
import scipy
print(scipy.__version__)
# Try numpy and matplotlib

3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
1.2.1


## The two most useful functions in Python
* `dir` - list all names (variables, functions, etc) in the given scope, i.e., what's in here? Try the following:
```
# top level name space
dir()
x = 1
dir()
```
```
import sys
# contents of the sys module
dir(sys)
```

* `help` - show documentation for a function or object.
```
import numpy as np
help(np.sum)
```

#### Use `dir` to see what's in the NumPy module. Pick a random function and see what it does.

In [2]:
dir()
x = 1
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'get_ipython',
 'quit',
 'scipy',
 'sys',
 'x']

## Best Practices

* Put module imports at the top in the first code cell.
* Rename modules to keep names short.
```
# Too long!
import numpy
x = numpy.arange(10)
```
```
# Much better
import numpy as np
x = np.arange(10)
```
* Don't do `from MODULE import *`. Every available object will be in your namespace.
```
from scipy import *
dir() # aaah!
```
* Be careful with variable names. Just about everything can be overwritten.
```
dir = 5
dir()
# The dir function is now lost. Doom.
```
* Use tab completion to recall function/object names. Start typing something and hit the [tab] key a couple times to bring up a menu of matching options. Use this in the terminal, too. Don't waste time typing long names.
```
np.su[tab][tab]
```
* If things are getting messy, restart the kernel using one of the *Restart* commands in the *Kernel* menu. This will reset your session, removing bad imports and extra variables.
* Cell taking too long to run? From *Kernel* menu, click *Interrupt* to stop execution. Have a look at the traceback to see where the code was. This can give a hint as to why it's taking so long.
* Keep it neat. Someone is most likely going to have to read your code someday. It should look nice, be clear, and conform to the style of code that was already there.

### Plotting tips
* add `%matplotlib inline` your import cell to get plots to show up in the notebook
```
from matplotlib import pyplot as plt
%matplotlib inline
```
* add the following in a separate cell to make defautl plot and font sizes bigger
```
pyplot.rcParams['figure.figsize'] = (10, 6) # inches
pyplot.rcParams['font.size'] = 14
```

# Activities

## Integer and floating point precision
Not all programming languages have fancy [arbitrary precision integers](https://rushter.com/blog/python-integer-implementation/). NumPy arrays of integers and floats will have limited precision.

#### Integer types
* `np.int8`, `np.int16`, `np.int32`, `np.int64`
* `np.uint8`, `np.uint16`, `np.uint32`, `np.uint64`

#### Floating point types
* `np.float16`, `np.float32`, `np.float64`, `np.float128`

Use the `np.iinfo` (for ints) and `np.finfo` (for floats) commands to see the limitations of some of these variable types, i.e. what do you get from `np.iinfo(np.int32)`?

In [3]:
import numpy as np

In [7]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

See what happens when an upper or lower limit is exceeded. Try a few different types.

In [8]:
x = np.array([125, 126, 127], dtype=np.int8)
print(x)
x += 1
print(x)

[125 126 127]
[ 126  127 -128]


Floating point numbers have an attribute called *resolution*. Demonstrate the meaning of this term with the array below.

In [17]:
y = np.array([1000, 100, 10, 1, 0.1], dtype=np.float32)
print(y,y*y)

[1.e+03 1.e+02 1.e+01 1.e+00 1.e-01] [1.0000000e+06 1.0000000e+04 1.0000000e+02 1.0000000e+00 1.0000001e-02]


## NumPy arrays: why bother?
NumPy arrays can be manipulated all at once without having to explicitly iterate over each value. NumPy operations are also significantly faster.

In [10]:
import time

In [12]:
# with lists
z = list(range(10000000))

t1 = time.time()
for i in range(len(z)):
    z[i] += 1
t2 = time.time()
print("That took %f seconds." % (t2-t1))

That took 1.255832 seconds.


In [13]:
# with arrays
z = list(range(10000000))
za = np.array(z)

t1 = time.time()
za += 1
t2 = time.time()
print("That took %f seconds." % (t2-t1))

That took 0.012720 seconds.


### Some useful NumPy array generator functions.
* `np.arange`
* `np.linspace`
* `np.logspace`
* `np.ones`, `np.ones_like`
* `np.zeros`, `np.zeros_like`

Try them out. Feel free to make notes for yourself.

AttributeError: module 'numpy' has no attribute 'arrange'

## Plotting
Some useful plotting commands:
* `plt.plot`
* `plt.semilogx`, `plt.semilogy`
* `plt.loglog`
* `plt.scatter`
* `plt.xlim`, `plt.ylim`
* `plt.xlabel`, `plt.ylabel`
* `plt.legend`
* `plt.title`
* `plt.xscale`, `plt.yscale`

See [here](https://matplotlib.org/api/pyplot_summary.html) for a list of all plotting commands.

When making plots for checkpoints, always label the axes. Make them look nice.

A Gaussian distribution with mean, $\mu$, and variance, $\sigma^2$, takes the form:

$
\begin{align}
\Large
f(x) = \frac{1}{2\pi\sigma^{2}} e^{-\frac{(x - \mu)^2}{2\sigma^{2}}}
\end{align}
$

Make a plot of this function over the range [-5, 5] for a couple values of $\mu$ and $\sigma$ with appropriate labels and a legend. Hint, the `label` keyword can be given to the plotting commands to aid in making the legend. Try different combinations of linear and log-space plots.

First, code up a function for the Gaussian distribution. We'll use it here and there.

In [ ]:
def my_gaussian(x, mu=0, sigma=1):
# YOUR CODE HERE
raise NotImplementedError()

Running the cell below will test your function with a few values.

In [ ]:
assert (my_gaussian(0) - 0.3989422804014327 < 1e-7)
assert (my_gaussian(1) - 0.24197072451914337 < 1e-7)

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline
import numpy as np

In [ ]:
plt.rcParams['figure.figsize'] = (10, 6) # inches
plt.rcParams['font.size'] = 14

In [ ]:
# Make plots here!

## Integration
Simple integration/summation can be done with basic array operations, i.e., not using fancy integration functions. Some useful functions:
* `np.sum`, `np.cumsum`

Note, many operations available directly from an array:
```
x = np.array([0, 1])
print (x.sum())
print (x.cumsum())
print (x.mean(), x.min(), x.max(), x.size)
```

Scipy has many [useful integration functions](https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html).

To import one of those, you'll need to do:
```
from scipy.integrate import FUNCTION
```

Note, some of the scipy integrators require a function be given as one of the arguments. Other expect arrays of values. Read their documentation.

Integrate the Gaussian distribution from -5$\sigma$ to +5$\sigma$ using a few of the integration functions, like the trapezoidal rule and Simpson's rule. How quickly do the answers converge as a function of the number of points used?

Bonus: approximations like the trapezoidal rule and Simpson's rule can be coded up as vector operations in a few lines. Try this if you feel like.